### ISSUE TITLE
Misc. style niceties

### ISSUE THREAD

**Issue by chriskrycho** [chriskrycho/v5.chriskrycho.com#4]
A mishmash of items, including some I wanted but never got to on v4:

- [x] Edit and issue links (chriskrycho/v4.chriskrycho.com#14, #37)
- [x] Source link pointing to file on GitHub (#37)
- [ ] Definition list styles (chriskrycho/v4.chriskrycho.com#40)
- [ ] Audio elements (chriskrycho/v4.chriskrycho.com#76)
- [ ] Video elements

**Comment by chriskrycho** [comment]
Calling this "done": I will add the others at such a time as I actually *need* them. Styles-on-demand.
